export const SEARCH = {
  SEARCH: "SEARCH",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAIL: "SEARCH_FAIL",
};

export const GET_DATA = {
  GET_DATA: "GET_DATA",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAIL: "GET_DATA_FAIL",
};

export const SORT_DATA = {
  SORT_DATA: "SORT_DATA",
  SORT_DATA_SUCCESS: "SORT_DATA_SUCCESS",
  SORT_DATA_FAIL: "SORT_DATA_FAIL",
};
